'use strict';

const randomItem = require('./randomItem.js');
var supports =
    [    
        "Added Chaos Damage",
        "Added Cold Damage",
        "Added Fire Damage",
        "Added Lightning Damage",
        "Additional Accuracy",
        "Advanced Traps",
        "Ancestral Call",
        "Arcane Surge",
        "Archmage",
        "Arrogance",
        "Arrow Nova",
        "Awakened Added Chaos Damage",
        "Awakened Added Cold Damage",
        "Awakened Added Fire Damage",
        "Awakened Added Lightning Damage",
        "Awakened Ancestral Call",
        "Awakened Arrow Nova",
        "Awakened Blasphemy",
        "Awakened Brutality",
        "Awakened Burning Damage",
        "Awakened Cast On Critical Strike",
        "Awakened Cast While Channelling",
        "Awakened Chain",
        "Awakened Cold Penetration",
        "Awakened Controlled Destruction",
        "Awakened Deadly Ailments",
        "Awakened Elemental Damage With Attacks",
        "Awakened Elemental Focus",
        "Awakened Fire Penetration",
        "Awakened Fork",
        "Awakened Generosity",
        "Awakened Greater Multiple Projectiles",
        "Awakened Hextouch",
        "Awakened Increased Area Of Effect",
        "Awakened Lightning Penetration",
        "Awakened Melee Physical Damage",
        "Awakened Melee Splash",
        "Awakened Minion Damage",
        "Awakened Multistrike",
        "Awakened Spell Cascade",
        "Awakened Spell Echo",
        "Awakened Swift Affliction",
        "Awakened Unbound Ailments",
        "Awakened Unleash",
        "Awakened Vicious Projectiles",
        "Awakened Void Manipulation",
        "Ballista Totem",
        "Barrage",
        "Blasphemy",
        "Blastchain Mine",
        "Blind",
        "Block Chance Reduction",
        "Bloodlust",
        "Bonechill",
        "Brutality",
        "Burning Damage",
        "Cast On Critical Strike",
        "Cast on Death",
        "Cast on Melee Kill",
        "Cast when Damage Taken",
        "Cast when Stunned",
        "Cast while Channelling",
        "Chain",
        "Chance to Bleed",
        "Chance to Flee",
        "Charged Mines",
        "Charged Traps",
        "Close Combat",
        "Cluster Traps",
        "Cold Penetration",
        "Cold to Fire",
        "Combustion",
        "Concentrated Effect",
        "Controlled Destruction",
        "Culling Strike",
        "Damage on Full Life",
        "Deadly Ailments",
        "Decay",
        "Efficacy",
        "Elemental Army",
        "Elemental Damage with Attacks",
        "Elemental Focus",
        "Elemental Penetration",
        "Elemental Proliferation",
        "Empower",
        "Endurance Charge on Melee Stun",
        "Energy Leech",
        "Enhance",
        "Enlighten",
        "Faster Attacks",
        "Faster Casting",
        "Faster Projectiles",
        "Feeding Frenzy",
        "Fire Penetration",
        "Fist of War",
        "Fork",
        "Fortify",
        "Generosity",
        "Greater Multiple Projectiles",
        "Greater Volley",
        "Hextouch",
        "High-Impact Mine",
        "Hypothermia",
        "Ice Bite",
        "Ignite Proliferation",
        "Immolate",
        "Impale",
        "Impending Doom",
        "Increased Area of Effect",
        "Increased Critical Damage",
        "Increased Critical Strikes",
        "Increased Duration",
        "Infernal Legion",
        "Infused Channelling",
        "Innervate",
        "Inspiration",
        "Intensify",
        "Iron Grip",
        "Iron Will",
        "Item Rarity",
        "Knockback",
        "Less Duration",
        "Lesser Multiple Projectiles",
        "Lesser Poison",
        "Life Gain on Hit",
        "Life Leech",
        "Lightning Penetration",
        "Maim",
        "Mana Leech",
        "Meat Shield",
        "Melee Physical Damage",
        "Melee Splash",
        "Minefield",
        "Minion Damage",
        "Minion Life",
        "Minion Speed",
        "Mirage Archer",
        "Multiple Totems",
        "Multiple Traps",
        "Multistrike",
        "Nightblade",
        "Onslaught",
        "Physical to Lightning",
        "Pierce",
        "Pinpoint",
        "Point Blank",
        "Poison",
        "Power Charge On Critical",
        "Predator",
        "Pulverise",
        "Rage",
        "Ruthless",
        "Second Wind",
        "Shockwave", 
        "Slower Projectiles",
        "Spell Cascade",
        "Spell Echo",
        "Spell Totem",
        "Stun",
        "Summon Phantasm",
        "Swift Affliction",
        "Swift Assembly",
        "Swiftbrand",
        "Trap and Mine Damage",
        "Trap",
        "Trinity",
        "Unbound Ailments",
        "Unleash",
        "Urgent Orders",
        "Vicious Projectiles",
        "Vile Toxins",
        "Void Manipulation",
        "Volley",
        "Withering Touch",
        "Earthbreaker",
        "Behead",
        "Focused Ballista"
    ]

    function randomSupport() {
        return randomItem.randomItem(supports);
    } 

    module.exports= {randomSupport: randomSupport};